### ISSUE TITLE
Change font to Cabin

### ISSUE THREAD

**Issue by rob93c** [rob93c/rob93c.github.io#3]
Use [Cabin](https://fonts.google.com/specimen/Cabin) as default font for the site.

**Comment by RajasekharGuptha** [comment]
Which Cabin style do you prefer ?

**Comment by rob93c** [comment]
Hi @RajasekharGuptha, sure you can!
I'd go with Cabin Regular

**Comment by RajasekharGuptha** [comment]
Can you check PR once

**Comment by rob93c** [comment]
Good job @RajasekharGuptha, you solved the issue!

**Comment by RajasekharGuptha** [comment]
Do you have any idea of adding this to Hacktoberfest?

**Comment by rob93c** [comment]
I'm not really sure if this project is suitable for Hacktoberfest to be honest

**Comment by RajasekharGuptha** [comment]
I think it is.
